### ISSUE TITLE
Most possibly a token grabber.

### ISSUE THREAD

**Issue by LegendStormieCZ** [SuppliedOrange/VALORANT-Instalocker#1]
This will most possibly grab your passwords or tokens, use at your own risk as this is a 99.9% grabber made in python.

**Comment by SuppliedOrange** [comment]
Thank you for informing us LegendStormieCZ. Yes this is infact a token-grabber. The code is totally not open-sourced and is disguised malware.

**Comment by LegendStormieCZ** [comment]
Or you know just upload a malware instead of the compiled source code.

**Comment by SuppliedOrange** [comment]
Well compile it yourself then? I think that's a much better alternative than to spread misinformation. ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

What I have here is the compiled code. I would like to see the sources for your 99.9% guarantee that this is malware. Have you reverse-engineered the .exe to find a token-grabber? I didn't think so.
