### ISSUE TITLE
[Feature Request] some ideas

### ISSUE THREAD

**Issue by operationairstrike** [SuppliedOrange/VALORANT-Instalocker#9]
like i need a feature that keeps the agent selected and keeps doing it for every round

**Comment by SuppliedOrange** [comment]
I like the idea. I could quickly make a fork since it's pretty easy to do so.
That aside, I'd also like to rebuild the whole repo from the ground up, I'm not satisfied with the way it is rn.

**Comment by operationairstrike** [comment]
sounds good hope soon xd

**Comment by operationairstrike** [comment]
@SuppliedOrange is there a auto updater built in?

**Comment by operationairstrike** [comment]
@SuppliedOrange what would also be cool is a auto start on game start switch

**Comment by SuppliedOrange** [comment]
@operationairstrike all of those features for a project this small feels like overkill. i think it would benefit from a revamp with those features rather than modifying this itself.

**Comment by operationairstrike** [comment]
I don't think it's overkill I think it makes it even better.

**Comment by operationairstrike** [comment]
And also I noticed it's like a website so I'm unable to tag it to the taskbar would be cool if you could make a portable exe that loads the site or whatever it is. But when I tried to pin it, it opened chrome after clicking it.
